### ISSUE TITLE
How to configure backends using yaml?

### ISSUE THREAD

**Issue by BoShurik** [ckfinder/ckfinder-symfony2-bundle#1]
Hello,

I am trying to set different `root` for `default` backend with this config:
```
ckfinder:
    connector:
        backends:
            default:
                root: '%kernel.root_dir%/../web/upload'
```
But I've got this configuration:
```
app/console debug:config ckfinder
# Current configuration for extension with alias: "ckfinder"
ckfinder:
    connector:
        backends: 
            symfony_cache: { name: symfony_cache, adapter: local, root: /Users/boshurik/Projects/skeleton/app/cache/dev }, 
            symfony_logs: { name: symfony_logs, adapter: local, root: /Users/boshurik/Projects/skeleton/app/logs }, 
            default: { name: default, adapter: local, baseUrl: /userfiles/, root: /Users/boshurik/Projects/skeleton/app/../web/userfiles, chmodFiles: 511, chmodFolders: 493, filesystemEncoding: UTF-8 }, 
            0: { root: /Users/boshurik/Projects/skeleton/app/../web/upload }
        # ...
```

Thank you!
